const books = [
  // BADIIY ADABIYOT
  {id:1, title:"O'tkan kunlar", author:"Abdulla Qodiriy", category:"badiiy", price:45000, lang:"uz", year:2022, pages:320, stock:15, rating:5, reviews:128, sales:450, bestseller:true, isNew:false, emoji:"📖", color:"#2c3e50", desc:"O'zbek adabiyotining durdonasi. Otabek va Kumushning sevgi qissasi – tarixiy roman."},
  {id:2, title:"Mehrobdan chayon", author:"Abdulla Qodiriy", category:"badiiy", price:42000, lang:"uz", year:2022, pages:280, stock:12, rating:5, reviews:95, sales:380, bestseller:true, isNew:false, emoji:"📕", color:"#8e44ad", desc:"Abdulla Qodiriyning ikkinchi mashhur romani. Anvar va Raʼno taqdiri."},
  {id:3, title:"Sariq devni minib", author:"Xudoyberdi To'xtaboyev", category:"badiiy", price:38000, lang:"uz", year:2023, pages:240, stock:20, rating:4, reviews:67, sales:290, bestseller:false, isNew:false, emoji:"📗", color:"#27ae60", desc:"Bolalar va o'smirlar sevib o'qiydigan ajoyib asar. Sarguzasht va sehrlarga to'la qissa."},
  {id:4, title:"Dunyoning ishlari", author:"O'tkir Hoshimov", category:"badiiy", price:35000, lang:"uz", year:2023, pages:300, stock:8, rating:4, reviews:54, sales:210, bestseller:false, isNew:true, emoji:"📘", color:"#2980b9", desc:"Hayot haqiqatlarini so'z vositasida aks ettirgan qissa va hikoyalar to'plami."},
  {id:5, title:"Shum bola", author:"G'afur G'ulom", category:"badiiy", price:32000, lang:"uz", year:2022, pages:200, stock:18, rating:5, reviews:112, sales:340, bestseller:true, isNew:false, emoji:"📙", color:"#e67e22", desc:"G'afur G'ulomning eng mashhur asari. Bolalik xotiralari va o'sha davr hayoti."},
  {id:6, title:"100 yillik yolg'izlik", author:"G. G. Markes", category:"badiiy", price:89000, lang:"uz", year:2023, pages:450, stock:6, rating:5, reviews:89, sales:180, bestseller:false, isNew:true, emoji:"📖", color:"#c0392b", desc:"Nobel mukofotiga sazovor bo'lgan dunyoga mashhur roman. Buendia oilasining yetti avlod tarixi."},
  {id:7, title:"Master va Margarita", author:"M. Bulgakov", category:"badiiy", price:75000, lang:"ru", year:2023, pages:480, stock:10, rating:5, reviews:143, sales:260, bestseller:true, isNew:false, emoji:"📕", color:"#6c3483", desc:"Rus adabiyotining eng buyuk asarlaridan biri. Shayton Moskvaga keladi..."},
  {id:8, title:"The Great Gatsby", author:"F.S. Fitzgerald", category:"badiiy", price:65000, lang:"en", year:2022, pages:180, stock:14, rating:4, reviews:76, sales:150, bestseller:false, isNew:false, emoji:"📗", color:"#1a5276", desc:"Amerika adabiyotining klassikasi. Boy va misteriyoz Gatsby haqida."},

  // ILMIY ADABIYOT
  {id:9, title:"Astronomiya", author:"A. Abdullayev", category:"ilmiy", price:55000, lang:"uz", year:2023, pages:350, stock:15, rating:4, reviews:42, sales:120, bestseller:false, isNew:true, emoji:"🔭", color:"#1a237e", desc:"Yulduzlar, sayyoralar va koinot haqida to'liq ma'lumot. Talabalar va o'quvchilar uchun."},
  {id:10, title:"Fizika kursi", author:"S. Mirzayev", category:"ilmiy", price:68000, lang:"uz", year:2023, pages:420, stock:20, rating:4, reviews:38, sales:200, bestseller:false, isNew:false, emoji:"⚗️", color:"#1565c0", desc:"11-sinf o'quvchilari va abituriyentlar uchun fizika fanini chuqur o'rganish uchun."},
  {id:11, title:"Psixologiya asoslari", author:"D. Karimov", category:"ilmiy", price:72000, lang:"uz", year:2024, pages:380, stock:12, rating:5, reviews:65, sales:180, bestseller:true, isNew:true, emoji:"🧠", color:"#4a148c", desc:"Insoniy xulq-atvor, his-tuyg'ular va aql-idrok haqida zamonaviy psixologiya."},
  {id:12, title:"Matematika olimpiadalari", author:"N. Tursunov", category:"ilmiy", price:48000, lang:"uz", year:2023, pages:290, stock:25, rating:4, reviews:55, sales:160, bestseller:false, isNew:false, emoji:"📐", color:"#006064", desc:"Olimpiada masalalari va yechim usullari. O'quvchilar va o'qituvchilar uchun."},

  // BOLALAR ADABIYOTI
  {id:13, title:"Qo'shiqli ertaklar", author:"Zulfiya Musayeva", category:"bolalar", price:28000, lang:"uz", year:2024, pages:120, stock:30, rating:5, reviews:88, sales:320, bestseller:true, isNew:true, emoji:"🌈", color:"#f57f17", desc:"Bolalar uchun qiziqarli ertaklar va she'rlar. Rangli rasmlar bilan bezatilgan."},
  {id:14, title:"Hayvonlar dunyosi", author:"S. Qodirov", category:"bolalar", price:32000, lang:"uz", year:2023, pages:150, stock:22, rating:4, reviews:71, sales:250, bestseller:false, isNew:false, emoji:"🦁", color:"#e65100", desc:"Bolalar uchun hayvonlar haqida qiziqarli ma'lumotlar va rasmlar."},
  {id:15, title:"Kichkina shahzoda", author:"A. de Saint-Exupéry", category:"bolalar", price:38000, lang:"uz", year:2023, pages:100, stock:18, rating:5, reviews:134, sales:390, bestseller:true, isNew:false, emoji:"⭐", color:"#1565c0", desc:"Dunyoning barcha tillarga tarjima qilingan eng mashhur bolalar kitoblaridan biri."},

  // TARIX
  {id:16, title:"O'zbekiston tarixi", author:"A. Sagdullayev", category:"tarix", price:78000, lang:"uz", year:2023, pages:500, stock:10, rating:4, reviews:48, sales:140, bestseller:false, isNew:false, emoji:"🏛️", color:"#4e342e", desc:"O'zbekiston tarixini to'liq qamrab olgan akademik nashr. Oliy ta'lim uchun."},
  {id:17, title:"Amir Temur", author:"B. Ahmedov", category:"tarix", price:65000, lang:"uz", year:2024, pages:380, stock:14, rating:5, reviews:92, sales:230, bestseller:true, isNew:true, emoji:"⚔️", color:"#37474f", desc:"Amir Temur hayoti, davlatchilik falsafasi va harbiy yurishlari haqida to'liq tarixiy asar."},

  // BIZNES
  {id:18, title:"Boylik qanday yaratiladi", author:"R. Kiyosaki", category:"biznes", price:95000, lang:"uz", year:2023, pages:280, stock:16, rating:5, reviews:156, sales:410, bestseller:true, isNew:false, emoji:"💰", color:"#1b5e20", desc:"«Kambag'al ota, boy ota» muallifi. Moliyaviy savodxonlik asoslari."},
  {id:19, title:"7 ta odat", author:"S. Kovi", category:"biznes", price:88000, lang:"uz", year:2023, pages:320, stock:20, rating:5, reviews:178, sales:480, bestseller:true, isNew:false, emoji:"📋", color:"#0d47a1", desc:"Juda samarali odamlarning 7 ta odati. Dunyo bo'ylab 40 million nusxa sotilgan."},
  {id:20, title:"Biznesni boshqarish", author:"P. Druker", category:"biznes", price:82000, lang:"ru", year:2022, pages:400, stock:8, rating:4, reviews:67, sales:160, bestseller:false, isNew:false, emoji:"📊", color:"#002171", desc:"Zamonaviy menejmentning otasi Drukerning asosiy asari."},

  // CHET TIL
  {id:21, title:"Ingliz tili grammatikasi", author:"M. Berdiyeva", category:"chet", price:52000, lang:"uz", year:2024, pages:360, stock:35, rating:4, reviews:89, sales:350, bestseller:true, isNew:true, emoji:"🇬🇧", color:"#b71c1c", desc:"Ingliz tilini mustaqil o'rganish uchun to'liq grammatika darsligi."},
  {id:22, title:"IELTS Preparation", author:"Cambridge", category:"chet", price:120000, lang:"en", year:2023, pages:400, stock:12, rating:5, reviews:112, sales:280, bestseller:true, isNew:false, emoji:"📝", color:"#004d40", desc:"IELTS imtihoniga to'liq tayyorgarlik. Barcha bo'limlar: Reading, Writing, Listening, Speaking."},
  {id:23, title:"Rus tili darsligi", author:"V. Ivanova", category:"chet", price:45000, lang:"ru", year:2023, pages:280, stock:20, rating:4, reviews:56, sales:190, bestseller:false, isNew:false, emoji:"🇷🇺", color:"#b71c1c", desc:"Boshlang'ich darajadan o'rta darajagacha rus tilini o'rgatuvchi kurs."},
  {id:24, title:"Nemis tili boshlang'ich", author:"N. Haydarov", category:"chet", price:58000, lang:"uz", year:2024, pages:300, stock:18, rating:4, reviews:34, sales:120, bestseller:false, isNew:true, emoji:"🇩🇪", color:"#1a237e", desc:"Nemis tilini noldan o'rganish uchun zamonaviy darslik."},
];
